version: '3.8'

services:
  postgres:
    container_name: postgres-sql
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maathru
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: maathru
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_ID: test@example.com
      EMAIL_PASSWORD: testpassword
      PORT: 8080
      JWT_SECRET_KEY: qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm
      JWT_ACCESS_TOKEN_EXPIRATION: 86400000
      JWT_REFRESH_TOKEN_EXPIRATION: 2592000000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres:
