services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maathru
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - maathru-network
  spring-boot-app:
    container_name: spring-backend
    build: ./
    ports:
      - "8080:8080"
    networks:
      - maathru-network
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  maathru-network:
    driver: bridge