spring:
  application:
    name: backend
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

#Server
server:
  port: ${PORT:8081}

#Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui.path: /swagger-ui.html

#Jwt configuration
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
